"""Added finalized flag in codebook

Revision ID: 6f0d5756ed99
Revises: cfa82c2e1fe1
Create Date: 2025-06-21 10:52:47.336313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0d5756ed99'
down_revision: Union[str, None] = 'cfa82c2e1fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codebooks', sa.Column('finalized', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codebooks', 'finalized')
    # ### end Alembic commands ###
