"""Added themes

Revision ID: cfa82c2e1fe1
Revises: 01824e3aeb24
Create Date: 2025-06-19 17:12:27.802902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa82c2e1fe1'
down_revision: Union[str, None] = '01824e3aeb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.add_column('codes', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('codes', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.drop_constraint('codes_parent_id_fkey', 'codes', type_='foreignkey')
    op.create_foreign_key(None, 'codes', 'themes', ['theme_id'], ['id'])
    op.drop_column('codes', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.create_foreign_key('codes_parent_id_fkey', 'codes', 'codes', ['parent_id'], ['id'])
    op.drop_column('codes', 'theme_id')
    op.drop_column('codes', 'group_name')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
