"""add_confidence_to_code_assignments

Revision ID: eb94fe65eb88
Revises: beeba770515e
Create Date: 2025-06-29 20:40:16.217593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb94fe65eb88'
down_revision: Union[str, None] = 'beeba770515e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_assignments', sa.Column('confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_assignments', 'confidence')
    # ### end Alembic commands ###
